### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by ghost** [huangjingxin/www#3]
导航网站做的非常棒，界面也很优美。我觉得如果可以把搜索框更加美化一下就更完美更加实用了。

![QQ浏览器截图20191113092620](https://user-images.githubusercontent.com/43264024/68724935-d9f51500-05f7-11ea-96d1-0f0efd509874.png)

**Comment by huangjingxin** [comment]
首先感谢你提的建议，想不到快被废弃的项目，还有人会过来评论。

我说一下我这样做的原因：
1. 我需要一个方便使用的搜索框，最好是悬浮在窗口上，不随页面滚动；
2. 我不需要复杂的功能，尽量简洁，只要本地搜索就好；
3. 我希望它能做到**边打字边出结果**，做到即时反馈；

我的解决方案：
1. 搜索栏悬浮置顶，因为手机上显示效果不好，干脆把手机上面的搜索栏隐藏；
2. 因为浏览器自带搜索引擎，直接使用地址栏的搜索功能就好，我把谷歌、百度这些内置进去会显得多余。也有可能个人习惯不一样吧，我更倾向于使用浏览器自带的，喏~
![image](https://user-images.githubusercontent.com/41430133/68748543-97532d00-0637-11ea-9a9b-7c4fb3feaf3e.png)
3. 因为做的是即时搜索，把搜索按钮也干掉了。

最后，我承认个人审美有点问题，确实做的不好看。

**Comment by ghost** [comment]
很感谢你的回复，其实我的想法可能比较传统落后了，因为觉得既然是做导航站，那么一般的搜索引擎应该是整合到网页更符合个人习惯。
坚持做下去，相信你可以做的很棒，很出名。加油大佬！

--------------原始邮件--------------
发件人："黄敬鑫 "<notifications@github.com&gt;;
发送时间：2019年11月13日(星期三) 下午5:18
收件人："huangjingxin/www" <www@noreply.github.com&gt;;
抄送："Writeup实验室 "<admin@writeup.top&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [huangjingxin/www] 提个小建议 (#3)
-----------------------------------

 
首先感谢你提的建议，想不到快被废弃的项目，还有人会过来评论。
 
我说一下我这样做的原因：
  
我需要一个方便使用的搜索框，最好是悬浮在窗口上，不随页面滚动；
 
我不需要复杂的功能，尽量简洁，只要本地搜索就好；
 
我希望它能做到边打字边出结果，做到即时反馈；
  
我的解决方案：
  
搜索栏悬浮置顶，因为手机上显示效果不好，干脆把手机上面的搜索栏隐藏；
 
因为浏览器自带搜索引擎，直接使用地址栏的搜索功能就好，我把谷歌、百度这些内置进去会显得多余。也有可能个人习惯不一样吧，我更倾向于使用浏览器自带的，喏~
 
 
因为做的是即时搜索，把搜索按钮也干掉了。
  
最后，我承认个人审美有点问题，确实做的不好看。

**Comment by huangjingxin** [comment]
我真的不是大佬，不过谢谢你的鼓励。
